# Generated by Django 3.0.4 on 2020-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mailbox_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='snippet',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
