# Generated by Django 3.0.4 on 2020-04-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200413_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='received_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='spam_counter',
            field=models.IntegerField(default=0),
        ),
    ]
