# Generated by Django 3.0.4 on 2020-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200415_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='history_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
