# Generated by Django 3.0.5 on 2020-04-23 15:56

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_mailbox_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='bayess_filter_sensibility',
            field=models.CharField(default='medium', max_length=7),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='blacklist',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
    ]
