# Generated by Django 3.0.5 on 2020-04-23 15:56

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200423_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='blacklist',
            field=picklefield.fields.PickledObjectField(default=list, editable=False),
        ),
    ]
