# Generated by Django 3.0.5 on 2020-04-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200423_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='blacklist',
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.MailBox')),
            ],
        ),
    ]
