# Generated by Django 3.0.5 on 2020-04-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200430_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='bayess_filter_sensibility',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=7),
        ),
    ]
