# Generated by Django 3.0.5 on 2020-04-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200430_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together={('mailbox', 'address')},
        ),
    ]
