# Generated by Django 3.0.5 on 2020-05-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200430_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together=set(),
        ),
    ]
